# Shared keybindings. kitty_mod is defined per-OS in ${KITTY_OS}.conf.

# Hints https://sw.kovidgoyal.net/kitty/kittens/hints
map kitty_mod+u kitten hints --type url
map kitty_mod+g kitten hints --type regex --regex "([a-zA-Z0-9_.~-]+(?:/[a-zA-Z0-9_.~-]+)+)(?::\d+)?" --program @

# App and window management
map kitty_mod+shift+w quit
map kitty_mod+w close_window_with_confirmation ignore-shell
map kitty_mod+ctrl+w close_tab
map kitty_mod+t new_tab_with_cwd
map kitty_mod+n new_os_window
map kitty_mod+r set_tab_title
map kitty_mod+shift+, load_config_file
map kitty_mod+, edit_config_file
map kitty_mod+d launch --cwd=current --location=vsplit
map kitty_mod+shift+d launch --cwd=current --location=hsplit
map alt+equal set_background_opacity +0.05
map alt+minus set_background_opacity -0.05
map alt+0 set_background_opacity default

# Tab navigation
map kitty_mod+shift+[ move_tab_backward
map kitty_mod+shift+] move_tab_forward
map kitty_mod+[ previous_tab
map kitty_mod+] next_tab
map kitty_mod+shift+t select_tab
map kitty_mod+1 goto_tab 1
map kitty_mod+2 goto_tab 2
map kitty_mod+3 goto_tab 3
map kitty_mod+4 goto_tab 4
map kitty_mod+5 goto_tab 5

# Pane navigation
map kitty_mod+h neighboring_window left
map kitty_mod+l neighboring_window right
map kitty_mod+k neighboring_window up
map kitty_mod+j neighboring_window down

# Pane movement
map kitty_mod+shift+h move_window left
map kitty_mod+shift+l move_window right
map kitty_mod+shift+k move_window up
map kitty_mod+shift+j move_window down

# Pane resizing
map kitty_mod+ctrl+h resize_window narrower 2
map kitty_mod+ctrl+l resize_window wider 2
map kitty_mod+ctrl+k resize_window taller 2
map kitty_mod+ctrl+j resize_window shorter 2

# Pane detaching
map kitty_mod+shift+n detach_window
map kitty_mod+shift+m detach_tab

# Scrolling
map kitty_mod+up scroll_line_up
map kitty_mod+down scroll_line_down
map kitty_mod+shift+up scroll_page_up
map kitty_mod+shift+down scroll_page_down
map kitty_mod+z scroll_to_prompt -1
map kitty_mod+x scroll_to_prompt 1

# Scrollback
map kitty_mod+f search_scrollback
map kitty_mod+shift+f show_scrollback
map kitty_mod+o show_last_command_output

# Utility shortcuts
map kitty_mod+ctrl+, debug_config
map kitty_mod+p command_palette

# Sessions
map kitty_mod+shift+s save_as_session --use-foreground-process --base-dir ~/.config/kitty/sessions
map kitty_mod+ctrl+s save_as_session --relocatable --use-foreground-process --match=session:. .
map kitty_mod+shift+c close_session
map kitty_mod+ctrl+c close_session .
map kitty_mod+/ goto_session ./sessions
map kitty_mod+shift+/ goto_session -1
