# General
allow_remote_control socket
listen_on unix:/tmp/$USER-kitty-{kitty_pid}.sock
confirm_os_window_close -1 count-background
remember_window_position yes
enabled_layouts splits
startup_session sessions/default.kitty-session

# Font and cursor
font_family JetBrainsMono Nerd Font Mono
cursor_shape beam
cursor_blink_interval 0.5
modify_font cell_width 95%
modify_font cell_height 135%
modify_font underline_position 6px
modify_font underline_thickness 140%

# Window appearance
dynamic_background_opacity yes
background_opacity 0.9
window_padding_width 10 8 0 8
enable_audio_bell no
inactive_text_alpha 0.5
mouse_hide_wait -1
scrollback_lines 10000
scrollback_pager nvim --cmd 'let g:kitty_scrollback = 1' --cmd 'set eventignore=FileType' +'nnoremap q ZQ' +'call nvim_open_term(0, {})' +'set nomodified nolist' +'$' -

# Tabs
tab_switch_strategy previous
tab_bar_edge top
tab_bar_margin_width 5
tab_bar_margin_height 3 0
tab_bar_style separator
tab_separator "  "
tab_bar_min_tabs 2

# hide non session tabs (initial)
tab_bar_filter session:~
tab_title_template "{index} {title}"
tab_title_max_length 20
active_tab_font_style bold
inactive_tab_font_style normal

# Misc
copy_on_select clipboard
clear_selection_on_clipboard_loss yes
env read_from_shell=PATH XDG_* EDITOR VISUAL LANG LC_*
shell_integration enabled
notify_on_cmd_finish unfocused
clear_all_shortcuts yes

# BEGIN_KITTY_THEME
# Tokyo Night
include current-theme.conf
# END_KITTY_THEME

include ${KITTY_OS}.conf
include keys.conf
