# Options
kitty_mod cmd
hide_window_decorations titlebar-only
macos_option_as_alt both
font_size 13.0

# Clipboard
map cmd+c copy_to_clipboard
map cmd+v paste_from_clipboard

# Font size
map cmd+equal change_font_size all +2.0
map cmd+minus change_font_size all -2.0
map cmd+0 change_font_size all 0
