[env]
MACOS_GHOSTTY_CONFIG = "Library/Application Support/com.mitchellh.ghostty/config.ghostty"

[tasks.tools]
description = "Install all tools"
run = '''
  mise use -g node@22.18
  mise use -g go@latest
  mise use -g bun@latest
  mise use -g rust@stable
  mise use -g fzf@latest
  mise use -g zoxide@latest
  mise use -g rg@latest
  mise use -g neovim@latest
  mise use -g eza@latest
  mise use -g ffmpeg@latest
  mise use -g fastfetch@latest
  mise use -g lazygit@latest
  mise use -g fd@latest
  mise use -g bat@latest
  mise use -g delta@latest
  mise use -g git-lfs@latest
  mise use -g tlrc@latest
  mise use -g yazi@latest

  mise use -g npm:vscode-langservers-extracted@latest
  mise use -g npm:@tailwindcss/language-server@latest
  mise use -g npm:@typescript/native-preview@latest
  mise use -g npm:@fsouza/prettierd@latest
  mise use -g npm:eslint_d@latest
  mise use -g npm:stylelint@latest
  mise use -g cargo:taplo-cli@latest
  mise use -g cargo:stylua@latest
  mise use -g go:github.com/a-h/templ/cmd/templ@latest
  mise use -g go:mvdan.cc/sh/v3/cmd/shfmt@latest

  if [ "$(uname -s)" = "Linux" ]; then
    sudo pacman -S --noconfirm --needed zsh
    sudo pacman -S --noconfirm --needed ghostty
    sudo pacman -S --noconfirm --needed lua-language-server
    sudo pacman -S --noconfirm --needed zls
  elif [ "$(uname -s)" = "Darwin" ]; then
    brew install zsh
    brew install --cask ghostty
    brew install lua-language-server
    brew install zls
  fi

  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
'''

[tasks.link]
description = "Link all configs"
depends = ["lazygit", "ghostty", "fd", "git", "ripgrep", "nvim", "kitty"]

[tasks.nvim]
hide = true
run = 'ln -sfn "$MISE_CONFIG_ROOT/nvim" "$HOME/.config/nvim"'

[tasks.lazygit]
hide = true
run = 'ln -sfn "$MISE_CONFIG_ROOT/lazygit" "$HOME/.config/lazygit"'

[tasks.ghostty]
hide = true
run = '''
  ln -sfn "$MISE_CONFIG_ROOT/ghostty" "$HOME/.config/ghostty"

  if [ "$(uname -s)" = "Darwin" ]; then
    mkdir -p "$HOME/Library/Application Support/com.mitchellh.ghostty"
    ln -sfn "$MISE_CONFIG_ROOT/$MACOS_GHOSTTY_CONFIG" "$HOME/$MACOS_GHOSTTY_CONFIG"
  fi
 '''

[tasks.fd]
hide = true
run = 'ln -sfn "$MISE_CONFIG_ROOT/fd" "$HOME/.config/fd"'

[tasks.git]
hide = true
run = 'ln -sfn "$MISE_CONFIG_ROOT/.gitconfig" "$HOME/.gitconfig"'

[tasks.ripgrep]
hide = true
run = 'ln -sfn "$MISE_CONFIG_ROOT/.ripgreprc" "$HOME/.ripgreprc"'

[tasks.kitty]
hide = true
run = 'ln -sfn "$MISE_CONFIG_ROOT/kitty" "$HOME/.config/kitty"'
